version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    restart: always
    volumes:
      - ./storage:/data
  file-service-java:
    build:
      context: ./
      dockerfile: ./java/Dockerfile
    container_name: file-service-java
    ports:
      - "8080:8080"
    restart: always
  file-service-kotlin:
    build:
      context: ./
      dockerfile: ./kotlin/Dockerfile
    container_name: file-service-kotlin
    ports:
      - "7070:8080"
    restart: always
